spring:

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true

logging:
  level:
    root: WARN
    reactor.ipc.netty.channel: ERROR
    org.springframework.web.reactive.function.client.ExchangeFunctions: ERROR

server.port: 8880
